# Generated by Django 3.0.3 on 2020-06-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200607_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
